### ISSUE TITLE
SQL Aliases

### ISSUE THREAD

**Issue by cyouh95** [zenbert5/capstone_musclehub#1]
Instead of writing out the table names each time, you could use aliases to help:

```python
df = sql_query('''
SELECT v.first_name, v.last_name, v.gender, v.email, v.visit_date, f.fitness_test_date, ...
FROM `visits` v
LEFT JOIN `fitness_tests` f 
ON (v.first_name = f.first_name 
    AND v.last_name = f.last_name 
    AND v.email = f.email
    )
...
WHERE v.visit_date >= '7-1-17'
''')
```

https://github.com/zenbert5/capstone_musclehub/blob/master/musclehub_project/capstone_musclehub.py#L22-L41

**Comment by zenbert5** [comment]
Totally missed that!  Thanks for the calling that out.
