### ISSUE TITLE
just_apps

### ISSUE THREAD

**Issue by cyouh95** [zenbert5/capstone_musclehub#3]
Alternatively, you could utilize the `is_application` column you've created to generate the `just_apps` DataFrame.

```python
just_apps = df[df.is_application == 'Application']
```

https://github.com/zenbert5/capstone_musclehub/blob/master/musclehub_project/capstone_musclehub.py#L90
https://github.com/zenbert5/capstone_musclehub/blob/master/musclehub_project/capstone_musclehub.py#L63

**Comment by zenbert5** [comment]
Gotcha.  Thanks for the feedback

**Comment by zenbert5** [comment]
Updated
