### ISSUE TITLE
Bar Graph Data

### ISSUE THREAD

**Issue by cyouh95** [zenbert5/capstone_musclehub#4]
Alternatively, you could specify your data like below instead of writing out each value. This method will be useful especially if you have a lot of data to plot.

```python
plot_data = app_pivot['Percent'].values
bar_input = range(len(app_pivot)
...
ax.set_yticks = ([0, 0.05, 0.10, 0.15, 0.20])
```

https://github.com/zenbert5/capstone_musclehub/blob/master/musclehub_project/capstone_musclehub.py#L141-L142
https://github.com/zenbert5/capstone_musclehub/blob/master/musclehub_project/capstone_musclehub.py#L150

**Comment by zenbert5** [comment]
Thanks for the coaching and feedback!  Make sense.

**Comment by zenbert5** [comment]
Definitely more efficient and elegant.  Thanks.  Updates made.
