### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [zenbert5/capstone_musclehub#5]
(Exceeds Expectations)

Great job on this project! You performed all the tests correctly and nice work on the graphs! I also liked the thought you've put into your presentation (such as including the thank you's in slide 2). One suggestion would be to elaborate on the overview/background a bit more.

As a further challenge, try designing your own A/B test and carrying out the analysis. This will be great practice for continuing to build your skills! As you work, look out for ways to simplify your code and see how you can most efficiently write the lines (#1, #4).

**Comment by zenbert5** [comment]
Appreciate the appraisal on the quality of the work and improvement ideas to the code.  It offers me pointers to reflect and to incorporate into my future work.  I do plan to do more stats reading and try out more tests; this stuff doesn't come easy.  It really has gotten better as I do more of the guided projects.  

Thanks again for your feedback!!
